### ISSUE TITLE
Backend Server Tests Needs Own Test Database

### ISSUE THREAD

**Issue by 5h3rr1ll** [code-goodbuy/goodbuy-nodejs#34]
At the moment the backend server tests depending on a locally running MongoDB.

We need to implement a way that the test is always running, also if the executor hasn't MongoDB installed.

Maybe with an in-memory-MongoDB or by spinning up a docker image of MongoDB.

**Comment by Darjusch** [comment]
Lets reconsider that i don't know if there is such a huge use-case and we still want the same functionality. 
Docker would be one solution but then the person needs docker which is also a dependency. 

For now i created a separate DB in our MongoDB so the tests don't run on the same DB as the local server. 
Commit: 6492574a624c8642d58bef5e89b304ca35e5ef57

If you disagree you can reopen the issue
