### ISSUE TITLE
logging broken after server.ts refactored

### ISSUE THREAD

**Issue by jwdotpark** [code-goodbuy/goodbuy-nodejs#37]
This
`morgan.token(
            "custom",
            "[:date[iso]] [:user-agent] [:http-version] [:method] [:url] [:status] [:total-time ms]"
        );`
token for log formatting is now inside the constructor and it seems it's out of scope. It's now just logging 'custom' string. 

Is it safe to move this custom token outside of class App? something like
![image](https://user-images.githubusercontent.com/38537908/116292305-d296dc80-a795-11eb-9ad0-4f7f9220bea4.png)
 I checked it's working that way but I'm not sure it's safe to move there cause I'm not familiar with OOP tbh 😂 morgan token would be global but it won't much of a trouble i guess.. @d-pettersson

**Comment by d-pettersson** [comment]
Please go ahead. I don't think it would be an issue. Maybe set it as 'private' so there's no access possible from outside the class? @jwdotpark
