### ISSUE TITLE
TimeStamp for Server logs

### ISSUE THREAD

**Issue by 5h3rr1ll** [code-goodbuy/goodbuy-nodejs#47]
In order to have a better overview of what happens when it would help if the server also logs a timestamp and not only this:

<img width="243" alt="image" src="https://user-images.githubusercontent.com/23193392/116975335-c9d76680-acbf-11eb-9580-c485dab98c39.png">

**Comment by jwdotpark** [comment]
![image](https://user-images.githubusercontent.com/38537908/117001974-46c80780-ace3-11eb-97e9-3051b109f772.png)

Logger formatting is fixed, It also logs on console when crud. PR coming with clean up here and there.
BTW should I remove runtime identifier like Postman in the pic? it's a bit verbose but it tells who's querying. let me know if you think it fits there or not

**Comment by 5h3rr1ll** [comment]
@jwdotpark now I actually like that you can see who is querying. 😊 Is your PR already merged or will you create a PR for it?

**Comment by jwdotpark** [comment]
@5h3rr1ll It was a trivial fix so i just merged it into another branch I'm working on rn - PR would come within a day or two

**Comment by Darjusch** [comment]
Awesome @jwdotpark ! don't forget to close the issue when the pull request is through and tag it with the PR number.

**Comment by jwdotpark** [comment]
fixed with #54 !
