### ISSUE TITLE
NoSQL Indexes

### ISSUE THREAD

**Issue by Darjusch** [code-goodbuy/goodbuy-nodejs#57]
We need to implement the indexes we agreed upon for our database

**Comment by 5h3rr1ll** [comment]
@Darjusch for our database or for the DB we dumped from OFF? And do we again agreed on? Did anybody document anything? 😅 @d-pettersson @jwdotpark

**Comment by Darjusch** [comment]
Yeah we wrote it in the wiki

**Comment by Darjusch** [comment]
Our db for off we already did some

**Comment by Darjusch** [comment]
#61
