### ISSUE TITLE
Get Products from OFF into our collection

### ISSUE THREAD

**Issue by Darjusch** [code-goodbuy/goodbuy-nodejs#58]
We have to filter products from the OFF collection and insert them into our collection in the correct format. 
Doesn't have to be all a few hundred or thousand should be enough

**Comment by 5h3rr1ll** [comment]
@Darjusch @d-pettersson @jwdotpark what do you think if we just filter all german products, for now, bring them into the right format and call that set of products v1.0.0? Like the version of the document schema. End then, when we have more collection for corporations and companies and so on, we create new document versions. What do you think? Like this our database has a nice set of products already and at the same time we don't have a lot of products in our DB which we might not even net and definitely don't need at this point in time.

**Comment by jwdotpark** [comment]
not sure how to do that yet but cleansing sounds great

plus it would be nice if we can add extra stuff close to every life for test/demo purpose - i could do that manually after clean up

**Comment by Darjusch** [comment]
I am right now trying to do that but it seems like they don't have the origin ger or germany i don't find german products.
Right now i am trying to filter the dataset by the following criteria:

{"brands": { $exists: true, $ne: null }, $where: 'this.code.length == 8 || 13', $where: 'this._id.length == 8 || 13', "product_name": { $exists: true, $ne: null } }

I will download the data run the filter then try to pull this data in a new collection and filter again so we get only the fields we need. ( id, product_name, brands, code)

**Comment by 5h3rr1ll** [comment]
@Darjusch but we did it already, filtering for german products. There is definitely this field:

{ manufacturing_places: "Germany" } and this field { origins_lc: "de" }

Since @d-pettersson already tried to clean up the OFF DB maybe it would make sense to dump the DB again since I have the feeling that a lot of documents are already missing this information, cause we didn't try to filter them before.

**Comment by Darjusch** [comment]
Yes you are right i just checked with your filters.
Should i look for a combination of both then?

**Comment by Darjusch** [comment]
This are 10 products after filtering: 

[products.txt](https://github.com/code-goodbuy/goodbuy-nodejs/files/6433450/products.txt)

**Comment by 5h3rr1ll** [comment]
10 out of 1.7 million isn't that much. 😁

**Comment by Darjusch** [comment]
Its only a sample i can get as much as we want

**Comment by Darjusch** [comment]
We now have 35600 sanitised products: https://cloud.mongodb.com/v2/603e142336cb5650d1d459c1#metrics/replicaSet/603e171aa4a01f5023f8b47d/explorer/dev/products/find
